# Generated by Django 5.1.5 on 2025-01-31 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profile_pics/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ProfilePicture',
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'seekers',
            },
        ),
        migrations.CreateModel(
            name='TalentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TalentCategory',
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('height_in_cm', models.FloatField(blank=True, null=True)),
                ('physical_description', models.CharField(blank=True, max_length=500, null=True)),
                ('talent_description', models.CharField(max_length=500)),
                ('weight_in_kg', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('profile_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='searchapp.profilepicture')),
            ],
            options={
                'db_table': 'Talent',
            },
        ),
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('achievements', models.CharField(blank=True, max_length=500, null=True)),
                ('experience', models.IntegerField()),
                ('project_details_links', models.BinaryField(blank=True, null=True)),
                ('projects_worked', models.CharField(blank=True, max_length=500, null=True)),
                ('talent_description', models.CharField(blank=True, max_length=500, null=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.talent')),
                ('talent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='searchapp.talentcategory')),
            ],
            options={
                'db_table': 'SkillProfile',
            },
        ),
    ]
